# Generated by Django 2.1 on 2018-09-26 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=50, verbose_name='视频名称')),
                ('image', models.ImageField(upload_to='static/images/%Y/%m', verbose_name='视频图片')),
                ('video_file', models.FileField(upload_to='static/video/')),
                ('title', models.CharField(max_length=256, verbose_name='视频html.url')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('video_type', models.CharField(choices=[('1', '综艺'), ('2', '电影'), ('3', '动漫'), ('4', '少儿'), ('5', '音乐'), ('6', '美剧'), ('7', '韩剧'), ('8', '体育'), ('9', '游戏'), ('10', '生活'), ('11', '科技'), ('12', '旅游')], max_length=10)),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='视频评论')),
            ],
            options={
                'verbose_name': '视频内容',
                'verbose_name_plural': '视频内容',
            },
        ),
    ]
