# Generated by Django 2.1 on 2018-09-26 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, verbose_name='用户名')),
                ('userpassword', models.CharField(max_length=40, verbose_name='密码')),
                ('isactive', models.BooleanField(default=True, verbose_name='是否激活')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='注册时间')),
                ('amount_of_money', models.IntegerField(default=0, verbose_name='充值金额')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱地址')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
