# Generated by Django 2.0.1 on 2018-10-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='static/banner/%Y%m', verbose_name='轮播图'),
        ),
    ]
